name: Continuous Integration

on: [push, pull_request]

jobs:
  links:
    name: Check links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Link Checker
      uses: peter-evans/link-checker@v1
      with:
        args: -v -r *.md
    - name: Fail if there were link errors
      run: exit ${{ steps.lc.outputs.exit_code }}

  build:
    name: CI tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check formatting with blake
      run: |
        black --check . --exclude generator/generators/protobuf
    - name: Lint with flake8
      run: |
        # The GitHub editor is 127 chars wide
        flake8 . --count --max-line-length=127 --statistics --exclude generator/generators/protobuf
    - name: Execute smoke test
      run: |
        python parsec_mock/parsec_mock.py &
        sleep 5
        python tests/mock_test.py
